// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXJQ3ZEe7ImYVOOPECH2K3_xODMGwM7g4',
    appId: '1:915829488789:web:bb5456d949e123f41f2f9c',
    messagingSenderId: '915829488789',
    projectId: 'social-media-app-c47f0',
    authDomain: 'social-media-app-c47f0.firebaseapp.com',
    storageBucket: 'social-media-app-c47f0.firebasestorage.app',
    measurementId: 'G-00BB5ZGNZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQtOWVcB7_17LN7adHq5nCmU-Kcl2ZRmU',
    appId: '1:915829488789:android:3e61633bf1d728a61f2f9c',
    messagingSenderId: '915829488789',
    projectId: 'social-media-app-c47f0',
    storageBucket: 'social-media-app-c47f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiFlrbFPYvilgxs2AIH0aVO0CWuS4W5Wk',
    appId: '1:915829488789:ios:453a3a913211ceba1f2f9c',
    messagingSenderId: '915829488789',
    projectId: 'social-media-app-c47f0',
    storageBucket: 'social-media-app-c47f0.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );
}
